service: java8-serverless
frameworkVersion: '>=1.2.0 <2.0.0'
provider:
  name: aws
  runtime: java8
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
        - xray:GetSamplingRules
        - xray:GetSamplingTargets
        - xray:GetSamplingStatisticSummaries
      Resource: '*'
package:
  artifact: build/distributions/java8-serverless.zip
plugins:
  - serverless-iam-roles-per-function
  - serverless-cf-vars
functions:
  Function:
    handler: Handler::handler
    description: !Sub
      - 'Stack #{StackTagName} Environment #{EnvironmentTagName} Function #{ResourceName}'
      - ResourceName: Function
    runtime: java8
    tracing: Active
    iamRoleStatements:
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
          - xray:GetSamplingRules
          - xray:GetSamplingTargets
          - xray:GetSamplingStatisticSummaries
        Resource: '*'
resources:
  Parameters:
    StackTagName:
      Type: String
      Description: Stack Name (injected by Stackery at deployment time)
      Default: java8-serverless
    EnvironmentTagName:
      Type: String
      Description: Environment Name (injected by Stackery at deployment time)
      Default: dev